### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by sofialog** [geraldo/geoparc-turisme#18]
Fer proves amb SVG...

**Comment by geraldo** [comment]
Por ahora los estilos de la capa origens_turisme viene del código del visor Openlayers y por lo tanto no tiene sentido hacerlo ahora mismo. En el caso que un día utilizamos estilos SLD generados por QGIS, entonces haría falta volver a los SVGs y hacer más pruebas.

**Comment by sofialog** [comment]
1. En el visor no es veuen ni museus ni exposicions a l’aire lliure
2. Nou color pictos cova: #f0efd6

**Comment by geraldo** [comment]
ad 1. nota para mi ya que queda pendiente: son justamente los 2 elementos con un guión en su nombre (') y parece que QGIS Server tiene un problema con eso ya que lo estoy cargando con un filtro tipo https://mapa.psig.es/qgisserver/wfs3/collections/origens_turisme/items.geojson?MAP=/home/geoparc/geoparc-turisme/geoparc-turisme.qgs&limit=1000&tipus_cat=Centre%20d%27Interpretaci%C3%B3
ad 2. según https://github.com/geraldo/geoparc-turisme/issues/25 creo que esta bien el picto de la cova, pero estaba mal el de exposicions a l’aire lliure

**Comment by geraldo** [comment]
- [x] Nuevos íconos
- [x] Cambiar colores
- [x] Els pictos llegendes, exposició a l’aire lliure,  els he construït com he pogut amb elements que he trobat a internet. El fons hauria de ser blanc, en comptes de gris. També em passa el mateix amb alguns altres. A veure si em podeu ajudar a homogeneïtzar-ho.
