### ISSUE TITLE
Faltan contenidos

### ISSUE THREAD

**Issue by geraldo** [geraldo/geoparc-turisme#22]
Fotos:
- [ ] https://mapa.psig.es/geoparc-turisme/fotos/081_Aquelarre%20de%20Serraspina.jpg
- [ ] null (campo imatge1 vacio en ruta o pois)

Textos:
- [ ] Muchos títulos/descripciones en español

**Comment by sofialog** [comment]
En las nuevas fotografías aún quedan pendientes... Habrá que informar a Xavi de las que faltan

**Comment by sofialog** [comment]
Xavi dijo que ya iría añadiendo estos contenidos por su cuenta
