### ISSUE TITLE
Reemplazar Mapa base

### ISSUE THREAD

**Issue by sofialog** [geraldo/geoparc-turisme#24]
Buscar si hi ha alguna alternativa pq es vegin millor les carreteres i els noms dels pobles quan fas zoom de detall

**Comment by geraldo** [comment]
Valorar usar vector map del ICGC: https://visors.icgc.cat/contextmaps/#12.13/42.19615/0.94212

Por ahora lo añadimos como opción adicional para que podamos compararlo...

**Comment by geraldo** [comment]
Por ahora usé la versión Raster WMTS del contextmaps, va bastante más rápido que el vector tiles. En todo caso, si luego lo queremos personalizar podemos hacer el cambio a vector tiles.

**Comment by geraldo** [comment]
> De base cartogràfica em triat aquesta de sota (la última de l’ICGC), però hauríem de rebaixar el color de les carreteres vermelles, de manera que no destaquin tant respecte a les rutes.

Por lo tanto hay que hacer el cambio a un mapa base vectorial.

**Comment by geraldo** [comment]
Veo que no es totalmente igual la capa de teselas vectoriales a la de raster. Se puede modificar todos los detalles con el editor visual (https://visors.icgc.cat/contextmaps/#12.13/42.19615/0.94212) y luego copiar la URL pinchando "Desa URL". Esta URL tengo que meter al código fuente del visor para aplicar este estilo.
