### ISSUE TITLE
Revisar con Microsoft Edge

### ISSUE THREAD

**Issue by geraldo** [geraldo/geoparc-turisme#37]
Vi que Xavi el otro día utilizó Microsoft Edge, lo podríamos revisar para ver si todo funciona correctamente? Yo estoy en Linux y hago revisiones con Firefox y Chrome.

**Comment by geraldo** [comment]
@sofialog puedes probar si ahora desapareció el scroll horizontal en Edge? en caso contrario porfa ponerme una captura

**Comment by sofialog** [comment]
> @sofialog puedes probar si ahora desapareció el scroll horizontal en Edge? en caso contrario porfa ponerme una captura
Parece que aún no....

![image](https://user-images.githubusercontent.com/98451889/222090645-fd8ba10b-6bb7-45fb-894f-c1c582b7b05f.png)

**Comment by sofialog** [comment]
> Tenias razón, ahora sí ! 😀

![image](https://user-images.githubusercontent.com/98451889/222094362-91dbceea-5445-4482-8caa-2e43d7c9e93f.png)
